<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>BackgroundWorkerApplication</RootNamespace>
    <AssemblyName>BackgroundWorkerApplication</AssemblyName>
    <LangVersion>latest</LangVersion>
    <CodePage>65001</CodePage>
  </PropertyGroup>

</Project>
