<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>GraphicsEditorBinding</RootNamespace>
    <AssemblyName>GraphicsEditorBinding</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
