<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>RoadSigns</RootNamespace>
    <AssemblyName>RoadSigns</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Images\*.png" />
    <None Include="Signs\*.svg" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
