<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>ParallelForApplication</RootNamespace>
    <AssemblyName>ParallelForApplication</AssemblyName>
    <LangVersion>latest</LangVersion>
    <CodePage>65001</CodePage>
  </PropertyGroup>

</Project>
